### ISSUE TITLE
Audio and Headphone

### ISSUE THREAD

**Issue by Askuccio** [DarkJoker360/android_device_huawei_hi6250#1]
Assuming to your remove_stuff https://github.com/DarkJoker360/android_device_huawei_hi6250/blob/android-9.0/remove_stuff/Android.mk

You need to include in your _device.mk_ the RemovePackages2

So, change:

**# Remove unwanted packages
PRODUCT_PACKAGES += \ \
    RemovePackages**

to

**# Remove unwanted packages
PRODUCT_PACKAGES += \ \
    RemovePackages \ \
    RemovePackages2**

Also, for fix the headphone disconnecting/connecting issue, you need to remove the /dev/input/event overlay:
    **
    <bool name="config_useDevInputEventForAudioJack">true</bool>**

yeah, remove. Credits to Dil3mm4: https://github.com/phhusson/vendor_hardware_overlay/commit/655dfabb9191600d29b39bd26e03793e8b719362

**Comment by DarkJoker360** [comment]
Hello, it is fixed now. Thanks for notice.
